version: '3.8'
services:
  eureka-service:
    build: eureka/
    container_name: eureka-service
    ports:
      - "8761:8761"

  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      - eureka-service
    ports:
      - "8080:8080"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  delivery-database:
    image: postgres:latest
    container_name: delivery-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=delivery-database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  delivery-service:
    build: delivery-service/
    container_name: delivery-service
    depends_on:
      - api-gateway
      - delivery-database
    ports:
      - "8081:8081"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  order-database:
    image: postgres:latest
    container_name: order-database
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=order-database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  order-service:
    build: order-service/
    container_name: order-service
    depends_on:
      - api-gateway
      - order-database
    ports:
      - "8082:8082"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  product-database:
    image: postgres:latest
    container_name: product-database
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_DB=product-database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  product-service:
    build: product-service/
    container_name: product-service
    depends_on:
      - api-gateway
      - product-database
    ports:
      - "8083:8083"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  recommendation-database:
    image: postgres:latest
    container_name: recommendation-database
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_DB=recommendation-database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  recommendation-service:
    build: recommendation-service/
    container_name: recommendation-service
    depends_on:
      - api-gateway
      - recommendation-database
    ports:
      - "8084:8084"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  user-database:
    image: postgres:latest
    container_name: user-database
    ports:
      - "5436:5436"
    environment:
      - POSTGRES_DB=user-database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  user-service:
    build: user-service/
    container_name: user-service
    depends_on:
      - api-gateway
      - user-database
    ports:
      - "8085:8085"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  vacancy-database:
    image: postgres:latest
    container_name: vacancy-database
    ports:
      - "5437:5437"
    environment:
      - POSTGRES_DB=vacancy-database
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  vacancy-service:
    build: vacancy-service/
    container_name: vacancy-service
    depends_on:
      - api-gateway
      - vacancy-database
    ports:
      - "8086:8086"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka