version: '3.8'
services:
  eureka-service:
    build: eureka/
    container_name: eureka-service
    ports:
      - "8761:8761"

  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on: [ eureka-service ]
    ports:
      - "8080:8080"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  delivery-service:
    build: delivery-service/
    container_name: delivery-service
    depends_on: [ api-gateway ]
    ports:
      - "8081:8081"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  order-service:
    build: order-service/
    container_name: order-service
    depends_on: [ api-gateway ]
    ports:
      - "8082:8082"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  product-service:
    build: product-service/
    container_name: product-service
    depends_on: [ api-gateway ]
    ports:
      - "8083:8083"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  recommendation-service:
    build: recommendation-service/
    container_name: recommendation-service
    depends_on: [ api-gateway ]
    ports:
      - "8084:8084"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  user-service:
    build: user-service/
    container_name: user-service
    depends_on: [ api-gateway ]
    ports:
      - "8085:8085"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka

  vacancy-service:
    build: vacancy-service/
    container_name: vacancy-service
    depends_on: [ api-gateway ]
    ports:
      - "8086:8086"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-service:8761/eureka